# This is a config for E2B sandbox template.
# You can use template ID (lap7zgoqf2b898rsmjdp) or template name (demo-nextjs-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("demo-nextjs-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("demo-nextjs-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('demo-nextjs-test2')

team_id = "1d0183de-f686-48d3-b688-0dccedab7739"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "demo-nextjs-test2"
template_id = "lap7zgoqf2b898rsmjdp"
